const dataMundial = [
   {
      "_id":"629c9c6b5749c4077500eaa8",
      "name_en":"Iran",
      "name_fa":"ایران",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/125px-Flag_of_Iran.svg.png",
      "fifa_code":"IRN",
      "iso2":"IR",
      "groups":"B",
      "id":"6",
      "description": "Selección nacional de fútbol de Irán, que ha participado en cuatro Copas del Mundo y es considerada una de las mejores selecciones de Asia."
   },
   {
      "_id":"629c9c6b5749c4077500eaa9",
      "name_en":"England",
      "name_fa":"انگلستان",
      "flag":"https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/125px-Flag_of_England.svg.png",
      "fifa_code":"ENG",
      "iso2":"ENG",
      "groups":"B",
      "id":"5",
      "description": "Selección nacional de fútbol de Inglaterra, uno de los equipos más exitosos y populares del mundo. Ha ganado la Copa del Mundo una vez y ha sido subcampeón en otras tres ocasiones."
   },
   {
      "_id":"629c9c6b5749c4077500eaaa",
      "name_en":"United States",
      "name_fa":"آمریکا",
      "flag":"https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/125px-Flag_of_the_United_States.svg.png",
      "fifa_code":"USA",
      "iso2":"US",
      "groups":"B",
      "id":"7",
      "description": "Selección nacional de fútbol de Estados Unidos, que ha participado en ocho Copas del Mundo y ha tenido un mayor éxito en torneos regionales como la CONCACAF Gold Cup."
   },
   {
      "_id":"629c9c6b5749c4077500eaab",
      "name_en":"Qatar",
      "name_fa":"قطر",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/125px-Flag_of_Qatar.svg.png",
      "fifa_code":"QAT",
      "iso2":"QA",
      "groups":"A",
      "id":"1",
      "description": "Selección nacional de fútbol de Qatar, que ha participado en tres Copas del Mundo y ha tenido éxito en torneos regionales como la AFC Asian Cup."
   },
   {
      "_id":"629c9c6b5749c4077500eaac",
      "name_en":"Ecuador",
      "name_fa":"اکوادور",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/125px-Flag_of_Ecuador.svg.png",
      "fifa_code":"ECU",
      "iso2":"Ec",
      "groups":"A",
      "id":"2",
      "description": "Selección nacional de fútbol de Ecuador, que ha participado en tres Copas del Mundo y ha tenido éxito en torneos regionales como la Copa América."
   },
   {
      "_id":"629c9c6b5749c4077500eaad",
      "name_en":"Senegal",
      "name_fa":"سنگال",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/125px-Flag_of_Senegal.svg.png",
      "fifa_code":"SN",
      "iso2":"SEN",
      "groups":"A",
      "id":"3",
      "description": "Selección nacional de fútbol de Senegal, que ha participado en una Copa del Mundo y ha tenido éxito en torneos regionales como la CAN."
   },
   {
      "_id":"629c9c6b5749c4077500eaae",
      "name_en":"Netherlands",
      "name_fa":"هلند",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/125px-Flag_of_the_Netherlands.svg.png",
      "fifa_code":"NL",
      "iso2":"NED",
      "groups":"A",
      "id":"4",
      "description": "Selección nacional de fútbol de Países Bajos, que ha participado en tres Copas del Mundo y ha sido finalista en dos ocasiones. Es conocida por su estilo de juego ofensivo y atractivo."
   },
   {
      "_id":"629c9c6b5749c4077500eab0",
      "name_en":"Argentina",
      "name_fa":"آرژانتین",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/125px-Flag_of_Argentina.svg.png",
      "fifa_code":"ARG",
      "iso2":"AR",
      "groups":"C",
      "id":"9",
      "description": "Selección nacional de fútbol de Argentina, que ha participado en veinte Copas del Mundo y ha ganado el torneo en dos ocasiones. Es uno de los equipos más exitosos y populares del mundo."
   },
   {
      "_id":"629c9c6b5749c4077500eab1",
      "name_en":"Saudi Arabia",
      "name_fa":"عربستان",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/125px-Flag_of_Saudi_Arabia.svg.png",
      "fifa_code":"KSA",
      "iso2":"SA",
      "groups":"C",
      "id":"10",
      "description":"Selección nacional de fútbol de Arabia Saudita, que ha participado en cuatro Copas del Mundo y ha tenido éxito en torneos regionales como la AFC Asian Cup."
   },
   {
      "_id":"629c9c6b5749c4077500eab2",
      "name_en":"Mexico",
      "name_fa":"مکزیک",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/125px-Flag_of_Mexico.svg.png",
      "fifa_code":"MEX",
      "iso2":"MX",
      "groups":"C",
      "id":"13",
      "description":"Selección nacional de fútbol de México, que ha participado en quince Copas del Mundo y ha sido subcampeón en una ocasión. Es uno de los equipos más populares y exitosos de América del Norte."
   },
   {
      "_id":"629c9c6b5749c4077500eab3",
      "name_en":"Poland",
      "name_fa":"لهستان",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/125px-Flag_of_Poland.svg.png",
      "fifa_code":"POL",
      "iso2":"PL",
      "groups":"C",
      "id":"14",
      "description":"Selección nacional de fútbol de Polonia, que ha participado en ocho Copas del Mundo y ha tenido éxito en torneos regionales como la UEFA European Championship."
   },
   {
      "_id":"629c9c6b5749c4077500eab4",
      "name_en":"France",
      "name_fa":"فرانسه",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg/125px-Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg.png",
      "fifa_code":"FRA",
      "iso2":"FR",
      "groups":"D",
      "id":"15",
      "description":"Selección nacional de fútbol de Francia, que ha participado en quince Copas del Mundo y ha ganado el torneo en dos ocasiones. Es uno de los equipos más exitosos y populares del mundo."
   },
   {
      "_id":"629c9c6b5749c4077500eab5",
      "name_en":"Australia",
      "name_fa":"استرالیا",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/125px-Flag_of_Australia_%28converted%29.svg.png",
      "fifa_code":"AUS",
      "iso2":"AU",
      "groups":"D",
      "id":"16",
      "description":"Selección nacional de fútbol de Australia, que ha participado en cuatro Copas del Mundo y ha tenido éxito en torneos regionales como la AFC Asian Cup."
   },
   {
      "_id":"629c9c6b5749c4077500eab6",
      "name_en":"Denmark",
      "name_fa":"دانمارک",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/125px-Flag_of_Denmark.svg.png",
      "fifa_code":"DEN",
      "iso2":"DK",
      "groups":"D",
      "id":"11",

      "description":"Selección nacional de fútbol de Dinamarca, que ha participado en cuatro Copas del Mundo y ha tenido éxito en torneos regionales como la UEFA European Championship."
   },
   {
      "_id":"629c9c6b5749c4077500eab7",
      "name_en":"Tunisia",
      "name_fa":"تونس",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/125px-Flag_of_Tunisia.svg.png",
      "fifa_code":"TUN",
      "iso2":"TN",
      "groups":"D",
      "id":"12",
"description"         :" Selección nacional de fútbol de Túnez, que ha participado en cuatro Copas del Mundo y ha tenido éxito en torneos regionales como la CAN."
   },
   {
      "_id":"629c9c6b5749c4077500eab8",
      "name_en":"Spain",
      "name_fa":"اسپانیا",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/125px-Flag_of_Spain.svg.png",
      "fifa_code":"ESP",
      "iso2":"ES",
      "groups":"E",
      "id":"21",
      "description":"elección nacional de fútbol de España, que ha participado en quince Copas del Mundo y ha ganado el torneo en una ocasión. Es uno de los equipos más exitosos y populares del mundo."
   },
   {
      "_id":"629c9c6b5749c4077500eab9",
      "name_en":"Costa Rica",
      "name_fa":"کاستاریکا",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/125px-Flag_of_Costa_Rica_%28state%29.svg.png",
      "fifa_code":"CRC",
      "iso2":"CR",
      "groups":"E",
      "id":"22",
      "description":"Selección nacional de fútbol de Costa Rica, que ha participado en cuatro Copas del Mundo y ha tenido éxito en torneos regionales como la CONCACAF Gold Cup."
   },
   {
      "_id":"629c9c6b5749c4077500eaba",
      "name_en":"Germany",
      "name_fa":"آلمان",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/125px-Flag_of_Germany.svg.png",
      "fifa_code":"GER",
      "iso2":"DE",
      "groups":"E",
      "id":"19",
      "description": "Selección nacional de fútbol de Alemania, que ha participado en quince Copas del Mundo y ha ganado el torneo en cuatro ocasiones. Es uno de los equipos más exitosos y populares del mundo."
   },
   {
      "_id":"629c9c6b5749c4077500eabb",
      "name_en":"Japan",
      "name_fa":"ژاپن",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/125px-Flag_of_Japan.svg.png",
      "fifa_code":"JPN",
      "iso2":"JP",
      "groups":"E",
      "id":"20",
      "description": "Selección nacional de fútbol de Japón, que ha participado en seis Copas del Mundo y ha tenido éxito en torneos regionales como la AFC Asian Cup."
   },
   {
      "_id":"629c9c6b5749c4077500eabc",
      "name_en":"Belgium",
      "name_fa":"بلژیک",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/125px-Flag_of_Belgium.svg.png",
      "fifa_code":"BEL",
      "iso2":"BE",
      "groups":"F",
      "id":"23",
      "description": "Selección nacional de fútbol de Bélgica, que ha participado en tres Copas del Mundo y ha tenido éxito en torneos regionales como la UEFA European Championship."
   },
   {
      "_id":"629c9c6b5749c4077500eabd",
      "name_en":"Canada",
      "name_fa":"کانادا",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/125px-Flag_of_Canada_%28Pantone%29.svg.png",
      "fifa_code":"CAN",
      "iso2":"CA",
      "groups":"F",
      "id":"24",
      "description": "Selección nacional de fútbol de Canadá, que ha participado en cuatro Copas del Mundo y ha tenido éxito en torneos regionales como la CONCACAF Gold Cup."
   },
   {
      "_id":"629c9c6b5749c4077500eabe",
      "name_en":"Morocco",
      "name_fa":"مراکش",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/125px-Flag_of_Morocco.svg.png",
      "fifa_code":"MAR",
      "iso2":"MA",
      "groups":"F",
      "id":"17",
      "description": "Selección nacional de fútbol de Marruecos, que ha participado en cuatro Copas del Mundo y ha tenido éxito en torneos regionales como la CAN."
   },
   {
      "_id":"629c9c6b5749c4077500eabf",
      "name_en":"Croatia",
      "name_fa":"کرواسی",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/125px-Flag_of_Croatia.svg.png",
      "fifa_code":"CRO",
      "iso2":"HR",
      "groups":"F",
      "id":"18",
      "description": "Selección nacional de fútbol de Croacia, que ha participado en cuatro Copas del Mundo y ha tenido éxito en torneos regionales como la UEFA European Championship."
   },
   {
      "_id":"629c9c6b5749c4077500eac0",
      "name_en":"Brazil",
      "name_fa":"برزیل",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/125px-Flag_of_Brazil.svg.png",
      "fifa_code":"BRA",
      "iso2":"BR",
      "groups":"G",
      "id":"25",
      "description": "Selección nacional de fútbol de Brasil, que ha participado en veinte Copas del Mundo y ha ganado el torneo en cinco ocasiones. Es uno de los equipos más exitosos y populares del mundo."
   },
   {
      "_id":"629c9c6b5749c4077500eac1",
      "name_en":"Serbia",
      "name_fa":"صربستان",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/125px-Flag_of_Serbia.svg.png",
      "fifa_code":"SRB",
      "iso2":"RS",
      "groups":"G",
      "id":"26",
      "description": "Selección nacional de fútbol de Serbia, que ha participado en dos Copas del Mundo y ha tenido éxito en torneos regionales como la UEFA European Championship."
   },
   {
     "_id":"629c9c6b5749c4077500eac2",
     "name_en":"Suiza",
     "name_fa":"سوئیس",
     "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/100px-Flag_of_Switzerland.svg.png",
     "fifa_code":"SUI",
     "iso2":"CH",
     "grupos":"G",
     "id":"31",
     "description": "La selección de fútbol de Suiza representa a Suiza en el fútbol internacional. El equipo está controlado por la Asociación Suiza de Fútbol. La mejor actuación de Suiza en la Copa Mundial de la FIFA es llegar a los cuartos de final tres veces, en 1934, 1938 y 1954 ."
  },
  {
     "_id":"629c9c6b5749c4077500eac3",
     "name_en":"Camerún",
     "name_fa":"کامرون",
     "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/125px-Flag_of_Cameroon.svg.png",
     "fifa_code":"CMR",
     "iso2":"CM",
     "grupos":"G",
     "id":"32",
     "description": "La selección de fútbol de Camerún representa a Camerún en el fútbol internacional. El equipo está controlado por la Fédération Camerounaise de Football. Camerún se ha clasificado para siete Copas Mundiales de la FIFA, más que cualquier otro equipo africano. Sin embargo, el equipo solo ha logrado una vez fuera de la fase de grupos"
  },
  {
     "_id":"629c9c6b5749c4077500eac4",
     "name_en":"Portugal",
     "name_fa":"پرتغال",
     "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/125px-Flag_of_Portugal.svg.png",
     "fifa_code":"POR",
     "iso2":"PT",
     "grupos":"H",
     "id":"27",
     "description": "La selección de fútbol de Portugal representa a Portugal en el fútbol de asociación internacional y está controlada por la Federación Portuguesa de Fútbol, ​​el organismo rector del fútbol en Portugal. Portugal ha participado en ocho finales de la Copa Mundial de la FIFA y se ha clasificado para el Campeonato de Europa de la UEFA trece veces"
  },
  {
     "_id":"629c9c6b5749c4077500eac5",
     "name_en":"Ghana",
     "name_fa":"Ejemplos",
     "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/125px-Flag_of_Ghana.svg.png",
     "fifa_code":"GHA",
     "iso2":"GH",
     "grupos":"H",
     "id":"28",
     "description": "La selección nacional de fútbol de Ghana representa a Ghana en el fútbol internacional y ha sido una de las selecciones de fútbol africanas más exitosas, ya que ganó la Copa Africana de Naciones cuatro veces y se clasificó para dos torneos de la Copa Mundial de la FIFA. Ghana también ha sido clasificado como uno de los mejores equipos de África"
  },
  {
     "_id":"629c9c6b5749c4077500eac6",
     "name_en":"Uruguay",
     "name_fa":"اروگوئه",
     "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/125px-Flag_of_Uruguay.svg.png",
     "fifa_code":"URU",
     "iso2":"UY",
     "grupos":"H",
     "id":"29",
     "description": "La selección de fútbol de Uruguay representa a Uruguay en el fútbol de asociación internacional y está controlada por la Asociación de Fútbol de Uruguay, el organismo rector del fútbol en Uruguay. El entrenador en jefe actual es Óscar Tabárez. La selección uruguaya se conoce comúnmente como La celeste"
  },
  {
     "_id":"629c9c6b5749c4077500eac7",
     "name_en":"Corea del Sur",
     "name_fa":"کره جنوبی",
     "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/125px-Flag_of_South_Korea.svg.png",
     "fifa_code":"COR",
     "iso2":"KR",
     "grupos":"H",
     "id":"30",
     "description": "La selección nacional de fútbol de Corea del Sur representa a Corea del Sur en el fútbol de asociación internacional y está controlada por la Asociación de Fútbol de Corea. Corea del Sur se ha clasificado para ocho Copas Mundiales de la FIFA y también ha llegado a las semifinales de la Copa Asiática de la AFC dos veces , en 1972 y 1980"
  },
  {
     "_id":"631064dab140f1214a8afc83",
     "name_en":"Gales",
     "name_fa":"ولز",
     "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Flag_of_Wales_%281959%29.svg/125px-Flag_of_Wales_%281959%29.svg.png",
     "fifa_code":"WAL",
     "iso2":"WLS",
     "grupos":"B",
     "id":"8",
     "description": "La selección nacional de fútbol de Gales representa a Gales en el fútbol internacional. Está controlada por la Asociación de Fútbol de Gales. El equipo juega sus partidos como local en el Cardiff City Stadium desde 2009. El equipo no se ha clasificado para un gran torneo desde la Copa Mundial de la FIFA de 1958"
  }
]